### ISSUE TITLE
Would like to know how to augment two image with the same style?

### ISSUE THREAD

**Issue by Owen-Liuyuxuan** [philipjackson/style-augmentation#1]
Many thanks for your library on style augmentation which boost my imagination.
I am thinking about using this augmentation on dual-camera setup.
I guess it may be better if I stylized two images in the same way, but don't know how to do it?
I would like to know the recommended way of controlling this ramdomness in this library

**Comment by srues2** [comment]
have you already figured out how to do this?

**Comment by Owen-Liuyuxuan** [comment]
Yes, I did.
Codes like:
```python
embedding = augmentator.sample_embedding(batch_size)
new_image_1 = augmentator(image_1, embedding=embedding)
new_image_2 = augmentator(image_2, embedding=embedding)
```
check the [style-augmentator API](https://github.com/philipjackson/style-augmentation/blob/master/styleaug/styleAugmentor.py)

**Comment by srues2** [comment]
> Yes, I did.
> Codes like:
> 
> ```python
> embedding = augmentator.sample_embedding(batch_size)
> new_image_1 = augmentator(image_1, embedding=embedding)
> new_image_2 = augmentator(image_2, embedding=embedding)
> ```
> 
> check the [style-augmentator API](https://github.com/philipjackson/style-augmentation/blob/master/styleaug/styleAugmentor.py)

Thank you Owen-Liuyuxuan :)
