### ISSUE TITLE
How can I stylize from a specific style image?

### ISSUE THREAD

**Issue by xuduo35** [philipjackson/style-augmentation#6]
I use get_embedding_mean_and_covariance.py to generate embedding. And change line 'im_restyled = augmentor(im_torch)' to 'im_restyled = augmentor(im_torch, alpha=alpha, embedding=embedding)', but seems not work. All the style images get the same result. Could weights in 'styleaug/checkpoints/checkpoint_stylepredictor.pth' is not right?

**Comment by CharlieCheckpt** [comment]
Hello, I have the exact same problem. Have you found a way to solve it @xuduo35 ?

**Comment by xuduo35** [comment]
No, I just give up.
